language: go

install:
  - go get -u -v github.com/Masterminds/glide
  - glide install --strip-vendor

script:
  - pwd
  - ls -l
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v cmd/storage
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v cmd/helm
  - docker build -t drbstaging.azurecr.io/bankdata/deployment-cleanup:git$TRAVIS_COMMIT .

before_deploy:
  - ./.travis/install-kube-tools.sh

deploy:
  - provider: script
    script: ./.travis/deploy.sh drbstaging.azurecr.io/bankdata/deployment-cleanup values.yaml
    on:
      branch: master
