language: go

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.13.2 && go install && cd -
  - glide install --strip-vendor

script:
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v cmd/...
  - docker build -t drbstaging.azurecr.io/bankdata/deployment-cleanup:git$TRAVIS_COMMIT .

before_deploy:
  - ./.travis/install-kube-tools.sh

deploy:
  - provider: script
    script: ./.travis/deploy.sh drbstaging.azurecr.io/bankdata/deployment-cleanup values.yaml
    on:
      branch: master
