---

# Values for deployment
image:
  pullSecret: regcred

env:
  - name: GITHUB_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: deployment-cleanup
        key: githubToken
  - name: AZURE_STORAGE_ACCOUNT_NAME
    valueFrom:
      secretKeyRef:
        name: deployment-cleanup
        key: azureAccountName
  - name: AZURE_STORAGE_ACCOUNT_KEY
    valueFrom:
      secretKeyRef:
        name: deployment-cleanup
        key: azureAccountKey

slugs:
  - "bankdata/relationsbank"
  - "kirbydesign/designsystem"
